if(CMAKE_BUILD_TYPE STREQUAL Release)
    if(NOT MSVC)
        unset(CMAKE_CXX_FLAGS_RELEASE CACHE)
        if(APPLE)
            set_compiler_flag_release(-O0)
            set_compiler_flag_release(-fno-inline)
        else()
            set_compiler_flag_release(-O1)
        endif()
    endif()

    message(STATUS "Release compiler flags are: ${CMAKE_CXX_FLAGS_RELEASE}")
elseif(CMAKE_BUILD_TYPE STREQUAL RelWithDebInfo)
    if(FOR_MACOSX)
        unset(CMAKE_C_FLAGS_RELWITHDEBINFO CACHE)
        unset(CMAKE_CXX_FLAGS_RELWITHDEBINFO  CACHE)
        set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O1 -gdwarf-2")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O1 -gdwarf-2")
    elseif(MSVC)
        # use default
    else()
        unset(CMAKE_CXX_FLAGS_RELWITHDEBINFO CACHE)
        set_compiler_flag_relwithdebinfo(-O1 -g)
    endif()
endif()
