set(CF_CED_LIBTYPE       SHARED)
set(CF_CUNEIFORM_LIBTYPE SHARED)
set(CF_LOAD_LIBTYPE      SHARED)

if(MINGW)
    set(CF_EXPORT_LIBTYPE      STATIC)
    set(CF_CUNEIFORM_LIBTYPE   STATIC)
    set(CF_LOAD_LIBTYPE        STATIC)
else()
    set(CF_EXPORT_LIBTYPE      SHARED)
    set(CF_CUNEIFORM_LIBTYPE   SHARED)
endif()


if(APPLE)
    set(CMAKE_EXE_LINKER_FLAGS "-framework Carbon")
endif()
