set(CPACK_SYSTEM_NAME i686)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Cuneiform optical recognition software")
set(CPACK_PACKAGE_VENDOR "Serj Poltavski")
set(CPACK_PACKAGE_VERSION_MAJOR ${CF_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${CF_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${CF_VERSION_PATCH})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/readme.txt")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING")
set(CPACK_PACKAGE_CONTACT "serj.poltavski@gmail.com")

if(WIN32 AND NOT UNIX)
  # There is a bug in NSI that does not handle full unix paths properly. Make
  # sure there is at least one set of four (4) backlasshes.
  #set(CPACK_PACKAGE_ICON "${CMake_SOURCE_DIR}/Utilities/Release\\\\InstallIcon.bmp")
  #set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\MyExecutable.exe")
  #set(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY} Cuneiform Optical Recognition Software")
  #set(CPACK_NSIS_HELP_LINK "https:\\\\\\\\code.launchpad.net/cuneiform-linux")
  #set(CPACK_NSIS_URL_INFO_ABOUT "https:\\\\\\\\code.launchpad.net/cuneiform-linux")
  #set(CPACK_NSIS_CONTACT "serj.poltavski@gmail.com")
  #set(CPACK_NSIS_MODIFY_PATH ON)
else()
  set(CPACK_BINARY_DEB ON)
  set(CPACK_BINARY_RPM OFF)
  set(CPACK_BINARY_TGZ ON)
  set(CPACK_BINARY_TBZ2 ON)
  set(CPACK_BINARY_TZ OFF)
  set(CPACK_BINARY_STGZ OFF)
  set(CPACK_STRIP_FILES "bin/cuneiform")
endif()

include(CPack)
