if(USE_WIN32_SHMEM)
    set(SUM_IPC "Win32")
elseif(USE_MMAP_SHMEM)
    set(SUM_IPC "MMap")
elseif(USE_SYSTEMV_SHMEM)
    set(SUM_IPC "SystemV")
endif()

message("                                                                      ")
message("                  Configure summary:                                  ")
message("                                                                      ")
message("    install directory:         ${CMAKE_INSTALL_PREFIX}                ")
message("    compiler:                  ${CMAKE_CXX_COMPILER}                  ")
message("    build type:                ${CMAKE_BUILD_TYPE}                    ")
message("    version:                   ${CF_VERSION}                          ")
message("    build number:              ${CF_BUILD_NUMBER}                     ")
message("    gui:                       ${CF_GUI}                              ")
message("    icon theme mac:            ${WITH_THEME_MAC}                      ")
message("    icon theme faenza:         ${WITH_THEME_FAENZA}                   ")
message("    icon theme gnome:          ${WITH_THEME_GNOME}                    ")
message("    icon theme human:          ${WITH_THEME_HUMAN}                    ")
message("    icon theme snowish:        ${WITH_THEME_SNOWISH}                  ")
message("    IPC type:                  ${SUM_IPC}                             ")
message("    image lib Qt4:             ${CF_USE_IMAGE_LIBRARY_QT}             ")
message("    image lib ImageMagick:     ${CF_USE_IMAGE_LIBRARY_IMAGE_MAGICK}   ")
message("    image lib GraphicsMagick:  ${CF_USE_IMAGE_LIBRARY_GRAPHICS_MAGICK}")
message("    image lib FreeImage:       ${CF_USE_IMAGE_LIBRARY_FREEIMAGE}      ")
message("    PDF support:               ${CF_PDF_SUPPORT}                      ")
message("    Multi TIFF support:        ${CF_TIFF_SUPPORT}                     ")
message("    C API:                     ${CF_API}                              ")
message("    sane support:              ${CF_SANE_SCANNER_SUPPORT}             ")
message("    CppCheck:                  ${CPPCHECK_FOUND}                      ")
message("    Doxygen:                   ${DOXYGEN_FOUND}                       ")
message("    package vendor:            ${CPACK_PACKAGE_VENDOR}                ")
message("    package generator:         ${CPACK_GENERATOR}                     ")
message("                                                                      ")
